"""Reminders: the vault tells the phone which tasks are due.

The tasks already carry dates; nothing rang. Once a day, and when the window
opens, the vault looks for tasks that are due tomorrow, today, or overdue and
not done, and knocks on the phone's door with them. The phone shows a
notification; tapping it opens the Tasks tab.

Rules kept small on purpose:
- one reminder per task per day, remembered in .tasks/reminded.json, so a
  window left open for a week does not nag every hour;
- the phone is reached through the same door and key the agent uses, read
  from .door/config.json; with no pairing there is nobody to remind and the
  vault says so in its status bar rather than failing;
- every reminder that reached the phone is a receipt on the PC as well.
"""

from __future__ import annotations

import ipaddress
import json
import re
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from .receipts import ReceiptLog
from .tasks import Task, TaskStore, view_task
from .dates import days_left

# Due within this many days counts as "coming up". Tomorrow, so a refill or a
# payment is not a surprise on the morning it is due.
HORIZON_DAYS = 1
TIMEOUT_S = 15
TAILNET = ipaddress.IPv4Network("100.64.0.0/10")


class InvalidDoorAddress(ValueError):
    """Pairing does not identify a direct tailnet HTTP destination."""


class InvalidDoorKey(ValueError):
    """Pairing does not contain the URL-safe token generated by the phone."""


class _NoDoorRedirects(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        # Even a redirect to another tailnet device is not the paired phone.
        return None


def _door_address(address: str) -> str:
    # Parse an exact literal, not a hostname: no DNS, credentials, URL suffixes,
    # control characters or alternative numeric-IP spellings can change routing.
    match = re.fullmatch(r"http://([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+):([0-9]{1,5})/?", address)
    if match is not None:
        try:
            host = ipaddress.IPv4Address(match[1])
            port = int(match[2])
            if host in TAILNET and 1 <= port <= 65535:
                return f"http://{host}:{port}"
        except ValueError:
            pass
    raise InvalidDoorAddress("phone address must be http://<100.64.0.0/10>:port")


@dataclass(frozen=True)
class Reminder:
    task_id: str
    title: str
    due: str
    days_left: int   # negative when overdue

    @property
    def when(self) -> str:
        if self.days_left < 0:
            return f"{-self.days_left} day(s) overdue"
        if self.days_left == 0:
            return "due today"
        return "due tomorrow" if self.days_left == 1 else f"due in {self.days_left} days"


def due_reminders(tasks: list[Task], today: date | None = None, horizon: int = HORIZON_DAYS) -> list[Reminder]:
    """Open tasks whose date is within the horizon or already past."""
    today = today or date.today()
    out: list[Reminder] = []
    for raw_task in tasks:
        t = view_task(raw_task)
        if t.done or not t.due:
            continue
        left = days_left(t.due, today)
        if left is None:
            continue
        if left <= horizon:
            out.append(Reminder(t.id, t.title, t.due, left))
    # most urgent first: overdue, then today, then tomorrow
    return sorted(out, key=lambda r: (r.days_left, r.title.lower()))


class RemindedLog:
    """Which task was reminded on which day. Small, human-readable, replaceable."""

    def __init__(self, tasks_dir: Path, log: ReceiptLog | None = None):
        self.file = Path(tasks_dir) / "reminded.json"
        self.log = log if log is not None else ReceiptLog(Path(tasks_dir).parent / ".receipts")
        self._data: dict[str, str] = {}
        self._load()

    def _load(self) -> None:
        self._data = {}
        if self.file.exists():
            try:
                self._data = json.loads(self.file.read_text(encoding="utf-8"))
            except ValueError:
                self._data = {}

    def already(self, task_id: str, today: date) -> bool:
        return self._data.get(task_id) == today.isoformat()

    def mark(self, task_id: str, today: date) -> None:
        with self.log.write("reminder_mark"):
            self._load()
            self.log.effect()
            try:
                self._data[task_id] = today.isoformat()
                self.file.parent.mkdir(parents=True, exist_ok=True)
                tmp = self.file.with_suffix(".json.tmp")
                tmp.write_text(json.dumps(self._data, indent=1, sort_keys=True), encoding="utf-8")
                tmp.replace(self.file)
                self.log.append("reminder_mark", task_id, self.file, extra={"day": today.isoformat()})
            except Exception:
                self._load()
                raise


def door_settings(root: Path) -> tuple[str, str] | None:
    """Address and key of the paired phone, or None when nothing is paired — or when the
    device that paired the door was revoked, even if its config was not removed yet."""
    cfg = Path(root) / ".door" / "config.json"
    if not cfg.exists():
        return None
    from .devices import DeviceRegistry
    if not DeviceRegistry(Path(root), None).door_owner_active():
        return None
    try:
        data = json.loads(cfg.read_text(encoding="utf-8"))
    except ValueError:
        return None
    address, key = str(data.get("address", "")).rstrip("/"), str(data.get("key", ""))
    return (address, key) if address and key else None


def knock(address: str, key: str, reminders: list[Reminder]) -> dict:
    """One call to the phone with everything due. Raises on no answer."""
    address = _door_address(address)
    if re.fullmatch(r"[A-Za-z0-9_-]+", key) is None:
        raise InvalidDoorKey("invalid phone key")
    body = json.dumps({
        "count": len(reminders),
        "items": [{"title": r.title, "due": r.due, "when": r.when} for r in reminders],
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{address}/door/remind", data=body, method="POST",
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), _NoDoorRedirects())
    with opener.open(req, timeout=TIMEOUT_S) as resp:
        return json.loads(resp.read())


def remind(root: Path, store: TaskStore, log: ReceiptLog, today: date | None = None) -> str:
    """Run one round. Returns a one-line status for the status bar."""
    if log.read_only:
        return "reminders: read-only"
    today = today or date.today()
    with log.write("reminder_check"):
        due = due_reminders(store.all(), today)
        if not due:
            return "reminders: nothing due"
        seen = RemindedLog(Path(root) / ".tasks", log)
        fresh = [r for r in due if not seen.already(r.task_id, today)]
        if not fresh:
            return f"reminders: {len(due)} due, already sent today"
        settings = door_settings(root)
        if settings is None:
            return f"reminders: {len(fresh)} due, but no phone is paired"
    # Phone I/O never holds the root guard. Persistence is admitted again below.
    address, key = settings
    try:
        answer = knock(address, key, fresh)
    except InvalidDoorAddress:
        return f"reminders: {len(fresh)} due, blocked phone address (requires http://<100.64.0.0/10>:port)"
    except InvalidDoorKey:
        return f"reminders: {len(fresh)} due, invalid phone key — pair the phone again"
    except (urllib.error.URLError, OSError, ValueError) as exc:
        # Transport errors may quote headers. Expose the category, never its
        # data-bearing diagnostic (which could contain the pairing secret).
        return f"reminders: {len(fresh)} due, phone did not answer ({type(exc).__name__})"
    if not answer.get("shown"):
        return f"reminders: phone refused ({answer.get('error', 'no reason')})"
    with log.write("remind"):
        for r in fresh:
            seen.mark(r.task_id, today)
            log.append("remind", r.title, address, note=f"{r.when} · shown on the phone",
                       extra={"task": r.task_id, "due": r.due})
    return f"reminders: {len(fresh)} sent to the phone"
